#!/usr/bin/env bash

CURRENT_PATH="$(dirname "${BASH_SOURCE[0]}")/_"
bind -f "${CURRENT_PATH}inputrc" 2>/dev/null #suppress stderr for non-interactive warning

for SOC_FILE in 'alias' 'history' 'prompt'; do
  # shellcheck disable=SC1090
  source "${CURRENT_PATH}${SOC_FILE}"
done
