#!/usr/bin/env bash

# shellcheck disable=SC2139
function _exist_cmd() {
  command -v "$1" &>/dev/null
}

[[ "$OSTYPE" =~ ^linux ]] && _PREFIX='sudo '
# if the system is Windows or user is root, sudo is not required
{ [[ "$OSTYPE" =~ ^msys ]] || [[ $(id -u) == '0' ]]; } && _PREFIX=''

# software or command alias
_exist_cmd docker && alias d='docker'
_exist_cmd vim && alias v="${_PREFIX}vim"
_exist_cmd npm && alias n='npm'
_exist_cmd yarn && alias ya='yarn'
_exist_cmd winpty && alias w='winpty'
_exist_cmd scoop && alias scp='scoop'
_exist_cmd code && alias co='code'
_exist_cmd busybox && alias b='busybox'

_exist_cmd pnpm && {
  alias p='pnpm'
  alias pb='pnpm build'
  alias px='pnpm dlx'
  alias pd='pnpm dev'
  alias pi='pnpm install'
  alias puni='pnpm uninstall'
  alias pse='pnpm serve'
  alias pst='pnpm start'
  alias pt='pnpm test'
}
_exist_cmd git && {
  alias ga='git add .'
  alias gc='git commit'
  alias gs='git status'
  alias gac='ga && gc -m'
}

# python virtual environments, use 'pyenv' create and activate virtual
_exist_cmd python && {
  alias pys='source ./venv/Scripts/activate'
  alias pyenv='python -m venv venv && pys'
}

# 'false' to 'true' to start alias
if false; then
  # personal proxy:
  #   pon           activate proxy for terminal
  #   poff          off proxy for terminal
  #   proxy         query proxy info
  _PROXY_URL='://127.0.0.1:7890'
  alias gpon="export https_proxy=http${_PROXY_URL} && echo -e 'https_proxy\ton';
export http_proxy=http$_PROXY_URL && echo -e 'http_proxy\ton';
export all_proxy=socks5$_PROXY_URL && echo -e 'all_proxy\ton'"
  alias gpoff='unset https_proxy && echo -e "https_proxy\toff";
unset http_proxy && echo -e "http_proxy\toff";
unset all_proxy && echo -e "all_proxy\toff";'

  alias pon='gpon'
  # shellcheck disable=SC2139
  alias poff="gpoff"

  _proxy='env |grep proxy;'
  #get the proxy address of the current environment variable
  alias proxy="$_proxy"
  _exist_cmd git && {
    alias gitpon="git config --global http.proxy http${_PROXY_URL};
git config --global https.proxy http${_PROXY_URL};
git config --global socks5.proxy socks5${_PROXY_URL}"
    alias gitpoff='git config --global --unset http.proxy;
git config --global --unset https.proxy;
git config --global --unset socks5.proxy'

    # if exist git, the alias will overwrite the privious
    alias proxy='git config --get --global http.proxy;
git config --get --global https.proxy;
git config --get --global socks.proxy;'"$_proxy"

    _poff='gitpoff && echo -e "git proxy\toff";'
    # shellcheck disable=SC2139
    _exist_cmd git && alias poff="$_poff""gpoff"
  }
fi

alias e='echo'
alias ..='cd ../'
alias ...='..;..'
alias ll='ls -al'

_exist_cmd ip || alias ip='ipconfig'

# personal workspace
WO="D:/Users/YeL/Documents/Code/"
[[ -d "$WO" ]] && alias wo="cd $WO"
